# created by eselect-repo

[rion]
location = /var/db/repos/rion
sync-type = git
sync-uri = https://github.com/rion-overlay/rion-overlay.git

[steam-overlay]
location = /var/db/repos/steam-overlay
sync-type = git
sync-uri = https://github.com/anyc/steam-overlay.git

[guru]
location = /var/db/repos/guru
sync-type = git
sync-uri = https://github.com/gentoo-mirror/guru.git

[underworld]
location = /var/db/repos/underworld
sync-type = git
sync-uri = https://github.com/DakEnviy/underworld-overlay.git

[vimproved]
location = /var/db/repos/vimproved
sync-type = git
sync-uri = https://codeberg.org/vimproved/overlay.git


[php-overlay]
location = /var/db/repos/php-overlay
sync-type = git
sync-uri = https://github.com/gentoo-php-overlay/php-overlay.git

[nest]
location = /var/db/repos/nest
sync-type = git
sync-uri = https://github.com/SpiderX/portage-overlay.git


[librewolf]
location = /var/db/repos/librewolf
sync-type = git
sync-uri = https://codeberg.org/librewolf/gentoo.git

[gentoo-zh]
location = /var/db/repos/gentoo-zh
sync-type = git
sync-uri = https://github.com/microcai/gentoo-zh.git

[xira]
location = /var/db/repos/xira
sync-type = git
sync-uri = https://github.com/kir68k/xira.git

[pf4public]
location = /var/db/repos/pf4public
sync-type = git
sync-uri = https://github.com/PF4Public/gentoo-overlay.git

